### ISSUE TITLE
Tabby.nvim highlighting

### ISSUE THREAD

**Issue by EpsilonKu** [lmburns/kimbox#5]
Idk, is it tabby.nvim or your colorscheme fault. It has problem with `TabLineSel`
![gscreenshot_2022-11-17-231339](https://user-images.githubusercontent.com/63652620/202512768-fd4159f4-7e23-4dd6-a909-ceb07280308b.png)

**Comment by lmburns** [comment]
I'm not sure. I have an issue that is similar on my end but it has to do with the Lualine plugin. I have changed the `TabLineSel` in the newest push. I'm not sure if that will fix your issue. It doesn't fix my issue with Lualine.

**Comment by lmburns** [comment]
I think your problem might be with your statusbar. I'm not sure if you are using Airline, but you can modify those highlight groups. Kimbox doesn't support airline

**Comment by lmburns** [comment]
I'm honestly not sure where the problem is coming from. If you would like to modify the airline code and submit a pull request that would be much appreciated. That is, if you are using Airline. I use Lualine and was thinking about removing support for Airline in the future, but if you would like to modify it, I could keep it. I will also do as much as I can in the meantime. I just do not have the plugin installed.

Note that I do have a similar issue with Lualine. This only occurs whenever `nvim-gps` is beside the `diff` plugin, and then the `nvim-gps` disappears because there is nothing to show.

![2022-11-17_13-32](https://user-images.githubusercontent.com/44355502/202545323-987a3160-f33f-4684-acb9-498f731c79db.png)

**Comment by EpsilonKu** [comment]
I will try to play with colors.
